name: pytorch2.0
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - cryptography=41.0.2=py311h22a60cf_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numpy=1.25.2=py311h08b1b3b_0
  - numpy-base=1.25.2=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.10=h7f8727e_2
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.2.1=py311h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - pytorch=2.0.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py311_cu118
  - torchtriton=2.0.0=py311
  - torchvision=0.15.2=py311_cu118
  - typing_extensions=4.7.1=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.26.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beartype==0.16.4
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.2
      - chardet==5.2.0
      - charset-normalizer==3.1.0
      - colt5-attention==0.10.19
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.14.4
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - deepspeed==0.11.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - dpkt==1.9.8
      - einops==0.7.0
      - evaluate==0.4.0
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - google-auth==2.25.2
      - google-auth-oauthlib==1.1.0
      - grpcio==1.60.0
      - hjson==3.1.0
      - huggingface-hub==0.16.4
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.0
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - local-attention==1.9.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - ninja==1.11.1.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - overrides==7.4.0
      - packaging==23.1
      - pamela==1.1.0
      - pandas==2.2.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - patsy==0.5.6
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==13.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==1.10.13
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.0
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - send2trash==1.8.2
      - seqeval==1.2.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - statsmodels==0.14.1
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.4
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.2
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - xxhash==3.3.0
      - yarl==1.9.2
